function PlotAltitude(t,Rcggs,C)

    n = numel(t);
    % []Number of elements in the time vector.

    hcg = zeros(1,n);
    % []Allocates memory for the altitude vector.

    for k = 1:n

        Rcge = C.Rgse + Rcggs(:,k);
        % [m]Vehicle positions WRT the Earth in ENZ coordinates.

        hcg(k) = norm(Rcge) - C.Re;
        % [m]Vehilce altitude above mean equator.

    end

    Window = figure( ...
        'Color','w', ...
        'Name','Altitude Above Mean Equator', ...
        'NumberTitle','Off');
    % []Opens a new window and adjusts its properties.

    Axes = axes( ...
        'FontName','Arial', ...
        'FontSize',12, ...
        'FontWeight','Bold', ...
        'NextPlot','Add', ...
        'Parent',Window, ...
        'XGrid','On', ...
        'YGrid','On', ...
        'XLim',[0,10], ...
        'YLim',[0,100], ...
        'XTick',linspace(0,10,11), ...
        'YTick',linspace(0,100,11));
    % []Adds an axes to the specified window and adjusts its properties.

    plot(t,hcg, ...
        'Color','k', ...
        'LineStyle','None', ...
        'Marker','.', ...
        'Parent',Axes);
    % []Adds a plot to the specified axes and adjusts its properties.

end
%===================================================================================================